build:
  image: ruby:2.3.1

  commands:
    - bundle install --jobs $(nproc) --path .bundle
    - bundle exec jekyll build
    - bundle exec htmlproofer ./_site

cache:
  mount:
    - .bundle
    - .git

deploy:
  rsync:
    delete: false
    host: xtian.us
    recursive: true
    source: _site
    target: /srv/www/xtian.us/public_html
    user: deploy
